# Generated by Django 5.1.3 on 2024-11-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_calle', models.CharField(max_length=30)),
                ('num_calle', models.CharField(max_length=30)),
                ('departamento', models.CharField(blank=True, max_length=4)),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nom_especialidad', models.CharField(max_length=50)),
                ('fec_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ult_actualizacion', models.DateField()),
                ('fec_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('fecha_abastecimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.IntegerField()),
                ('vigencia_licencia', models.DateField()),
                ('nom_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenHistorial',
            fields=[
                ('id_exa_his', models.AutoField(primary_key=True, serialize=False)),
                ('fec_creacion', models.DateField()),
                ('nom_examen', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], max_length=10)),
                ('resultados', models.TextField()),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='ControlHistorial',
            fields=[
                ('id_control_his', models.AutoField(primary_key=True, serialize=False)),
                ('fec_control', models.DateTimeField()),
                ('estado_control', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente')], max_length=10)),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id_farmacia', models.AutoField(primary_key=True, serialize=False)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionHistorial',
            fields=[
                ('id_observacion_his', models.AutoField(primary_key=True, serialize=False)),
                ('fec_creacion', models.DateField()),
                ('detalle', models.TextField()),
                ('diagnostico_medico', models.TextField()),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_completo', models.CharField(max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fec_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.direccion')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.medico')),
            ],
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.paciente'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('rut_completo', models.CharField(max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fec_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('fec_contratacion', models.DateField()),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.personal'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('id_sector', models.IntegerField()),
                ('nom_cargo', models.CharField(max_length=50)),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=50, unique=True)),
                ('hk_contrasena', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.personal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaHistorial',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fec_creacion', models.DateField()),
                ('dispensacion_meses', models.IntegerField()),
                ('indicacion', models.TextField()),
                ('cant_prescrita', models.IntegerField()),
                ('cant_entregada', models.IntegerField()),
                ('estado_gral', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], max_length=10)),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacion', models.TextField()),
                ('cant_prescrita', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='authentication.recetahistorial')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='id_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.sector'),
        ),
        migrations.CreateModel(
            name='EspecialidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.especialidad')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.medico')),
            ],
            options={
                'unique_together': {('id_medico', 'id_especialidad')},
            },
        ),
        migrations.CreateModel(
            name='PacienteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.paciente')),
            ],
            options={
                'unique_together': {('id_medico', 'id_paciente')},
            },
        ),
    ]
